## Basic Configuration

baseurl = "http://zujko.xyz" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Peter Zujko"
title = "Peter Zujko"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "zujko" # Comment out to disable Disqus.
googleAnalytics = "UA-90971126-2"
enableRobotsTXT = true

## Site Settings
[params]
author = "Peter Zujko"
intro = "Developer • CS Student"
description = "Computer Science major at RIT."
authorimage = "profile.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Peter Zujko's blog"
keywords = "zujko,blog,developer"

## Social Accounts
[params.social]
github = "zujko"
twitter = "PeterZujko"
linkedin = "zujko"
email = "peter@zujko.xyz"
#instagram = "<username>"
#facebook = "<username>"
#google = "<username>"
#stackoverflow = "<username>"

## Extras
[params.extra]
copyright = "© 2017 Peter Zujko" 
poweredby = true
hightlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "résumé"
    identifier = "résumé"
    weight = 200
    url = "/resume.pdf"
